apiVersion: apps/v1
kind: Deployment
metadata:
  name: lembretes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lembretes
  template:
    metadata:
      labels:
        app: lembretes
    spec:
      containers:
        - name: lembretes
          image: henriquebc/lembretes
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: lembretes-clusterip-service
spec:
  selector:
    app: lembretes
  type: ClusterIP
  ports:
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000